# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
