# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelves', '0003_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookshelf',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bookshelves.Bookshelf'),
        ),
    ]
